### ISSUE TITLE
npm run gulp not working

### ISSUE THREAD

**Issue by aakyel** [froala/design-blocks#65]
npm ERR! Windows_NT 10.0.17025
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! froala-design-blocks@1.0.2 gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the froala-design-blocks@1.0.2 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the froala-design-blocks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs froala-design-blocks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls froala-design-blocks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\...\Desktop\...\Free Templates\design-blocks\npm-debug.log

Help?

**Comment by CallumHemsley** [comment]
Am also getting this. Curious as to why no reply in a couple of days?

**Comment by alexanderldavis** [comment]
It seems you might need to upgrade your node.js and npm versions. In the error it suggests you `Make sure you have the latest version of node.js and npm installed`, and it seems to be saying you are currently using v6.11.0 of node and v3.10.10 of npm. I think the newest version of node is 8.x or 9.x, right? I don't know if that's what's wrong but that might be the issue.

**Comment by Korver2017** [comment]
I got the same info, and my node.js is v6.11.0, too. I fixed the problem after I installed the latest recommended version, v8.9.3.

**Comment by MaxShalom** [comment]
Gulp linked to this article in the command line, maybe it will help:
[Medium: The Problem with gulp-util](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5)

**Comment by Soo-Q6** [comment]
@Korver2017  i got that error, too. And i update my node.js from v6.11.0 to v8.9.4. But there are still an error, it says "Error: cannot find module 'gulp-watch'. And it occur in 'module.js:540'.

**Comment by MaxShalom** [comment]
That's what I am still getting. Still haven't found a fix.

**Comment by stefanneculai** [comment]
@Soo-Q6 @MaxShalom could you please run `npm install` once again?

**Comment by MaxShalom** [comment]
I updated everything. Node.js is now on `8.9.0` and npm is on `5.6.0`. I still get the below errors when trying to run `npm run gulp` in the project directory.

```
npm ERR! missing script: gulp
```

However, there is a `gulpfile.js` in the directory. What could be wrong?

**Comment by stefanneculai** [comment]
@MaxShalom does it work if you run the following:

```bash
rm -r node_modules
npm install
```

**Comment by Soo-Q6** [comment]
i reinstall my node and run `npm run gulp`, and this time it says that "Error: cannot find module 'puppeteer' " Then i try to `npm install puppeteer  --save-dev`. Stiill, it failed. how can i fix it? @stefanneculai

**Comment by Soo-Q6** [comment]
i found that i cannot access the source code of module **node-sass**(some problems of Chinese network environment), so i modify the file **.npmrc**, adding such configuration: `sass_binary_site=https://npm.taobao.org/mirrors/node-sass/` and it finally worked.
